name = "protocol-stats"
main = "./src/index.ts"
compatibility_date = "2023-05-18"

account_id = "<YOUR_ACCOUNT_ID_HERE>"

zone_id = "<YOUR_ZONE_ID_HERE>"
route = "<YOUR_URL_HERE>/*"

kv_namespaces = [
  { binding = "PROTOCOL_STATS", id = "<YOUR_KV_ID_HERE>", preview_id = "<YOUR_PREVIEW_KV_ID_HERE>" }
]

[triggers]
crons = ["0 */12 * * *"]